export default {
    ADD_TRANSACTION: 'ADD_TRANSACTION',
    UPDATE_TRANSACTION: 'UPDATE_TRANSACTION',
    REMOVE_TRANSACTION: 'REMOVE_TRANSACTION',

    SET_INPUT_ID: 'SET_INPUT_ID',
    SET_INPUT_TITLE: 'SET_INPUT_TITLE',
    SET_INPUT_VALUE: 'SET_INPUT_VALUE',
    RESET_INPUT: 'RESET_INPUT',
}