export default {
    ADD_TRANSACTION: 'ADD_TRANSACTION',
    UPDATE_TRANSACTION: 'UPDATE_TRANSACTION',
    REMOVE_TRANSACTION: 'REMOVE_TRANSACTION',
    SET_SELECTED_TRANSACTION: 'SET_SELECTED_TRANSACTION',
}